name: RDP with ngrok
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 10000

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure RDP Settings
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1 -Force

      - name: Create RDP User
        run: |
          $password = "A@405060"
          $securePass = ConvertTo-SecureString $password -AsPlainText -Force
          if (-not (Get-LocalUser -Name "ASEEL5" -ErrorAction SilentlyContinue)) {
              New-LocalUser -Name "ASEEL5" -Password $securePass -AccountNeverExpires
          }
          Add-LocalGroupMember -Group "Administrators" -Member "ASEEL5"
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "ASEEL5"
          echo "RDP User: ASEEL5"
          echo "RDP Password: $password"

      - name: Download and Setup ngrok
        run: |
          # تنزيل ngrok
          Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip" -OutFile "ngrok.zip"
          # فك ضغط الملف
          Expand-Archive ngrok.zip
          # نقل الملف التنفيذي إلى مسار يمكن الوصول إليه بسهولة
          Move-Item -Path "ngrok-v3-stable-windows-amd64\ngrok.exe" -Destination "C:\Windows\System32\"

      - name: Establish ngrok Tunnel
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          # مصادقة ngrok
          ngrok authtoken $env:NGROK_AUTH_TOKEN
          # تشغيل النفق في الخلفية
          Start-Process -FilePath "ngrok.exe" -ArgumentList "tcp 3389 --log=stdout" -NoNewWindow -RedirectStandardOutput "ngrok.log"

      - name: Display RDP Connection Info
        run: |
          Start-Sleep -s 10 # انتظر قليلاً حتى يبدأ ngrok ويعطي العنوان
          # استخراج عنوان TCP من سجلات ngrok
          $tcp_address = (Get-Content ngrok.log | Select-String "url=tcp://(.+ )" | ForEach-Object { $_.Matches.Groups[1].Value })
          if ($tcp_address) {
            Write-Host "`n=== RDP ACCESS ==="
            Write-Host "Address: $tcp_address"
            Write-Host "Username: ASEEL5"
            Write-Host "Password: A@405060"
            Write-Host "==================`n"
          } else {
            Write-Error "Failed to get ngrok TCP address. Check logs."
            Get-Content ngrok.log
            exit 1
          }
          
      - name: Maintain Connection
        run: |
          while ($true) {
              Write-Host "[$(Get-Date)] RDP Active - Use Ctrl+C in workflow to terminate"
              Start-Sleep -Seconds 300
          }
